[package]
name = "sar-core"
edition = "2021"
license.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
ages-prs = { workspace = true }
blowfish = { workspace = true }
image = { workspace = true }
thiserror = { workspace = true }
imageproc = { workspace = true }
rayon = "1.10.0"

[[example]]
name = "parse"
